ls:
    .dir: camelCase
    .js: camelCase
    .json: camelCase
    .ts: camelCase
    .tsx: camelCase
    .spec.ts: camelCase

ignore:
    - .git
    - .github
    - .idea
    - .ls-lint.yml
    - .eslintrc.js
    - .nyc_output
    - .husky
    - node_modules
    - docker
    - dist
    - "@types"
